class AllAnime {
  String name;
  String episodes;
  String image;
  bool unLiked;


  AllAnime({required this.unLiked,required this.name,required this.episodes,required this.image});
}

final allAnimeListRow = [
 AllAnime(unLiked: true, name: '', episodes: '12', image: 'assetses/img/img_34.png'),
 AllAnime(unLiked: true, name: "Gamers", episodes: "12", image: "assetses/img/img_35.png"),
 AllAnime(unLiked: true, name: "Over the sky", episodes: 'Full', image: 'assetses/img/img_33.png'),
 AllAnime(unLiked: true, name: 'Joshikausei', episodes: '12', image: 'assetses/img/img_25.png'),
 AllAnime(unLiked: true, name: 'Hybrid x Heart ', episodes: '12', image: 'assetses/img/img_19.png'),
 AllAnime(unLiked: true, name: 'Romantic Killer', episodes: '12', image: 'assetses/img/img_14.png'),
 AllAnime(unLiked: true, name: 'the dedective os already dead', episodes: '12', image: 'assetses/img/img_13.png'),
 AllAnime(unLiked: true, name: 'Love And Lies', episodes: '12', image: 'assetses/img/img_5.png'),
 AllAnime(unLiked: true, name: 'The great Demon lord reborn as a nobody', episodes: '12', image: 'assetses/img/img_4.png'),
 AllAnime(unLiked: true, name: 'The galaxy next door', episodes: '12', image: 'assetses/img/img_3.png'),
 AllAnime(unLiked: true, name: 'Actually I am ...', episodes: '12', image: 'assetses/img/img_2.png'),
 AllAnime(unLiked: true, name: 'Black Summoner', episodes: '12', image: 'assetses/img/img_1.png'),
 AllAnime(unLiked: true, name: 'The Genius Princess Guide To Raising a Nation out of Dept', episodes: '12', image: 'assetses/img/img.png'),
 AllAnime( unLiked: true,name: 'The Eminence in Shadow S1', episodes: '20', image: 'assets/img/img.png',),
 AllAnime( unLiked: false,name: 'My Star', episodes: '12', image: 'assets/img/img_1.png'),
 AllAnime( unLiked: false,name: 'The Angel Next Door Spoils Me Rotten', episodes: '12', image: 'assets/img/img_2.png'),
 AllAnime( unLiked: true,name: "An Archdemon's Dilemma: How to Love Your Elf Bride", episodes: 'Future', image: 'assets/img/img_4.png'),
 AllAnime( unLiked: true,name: 'The 100 Girlfriend who Really Loves You', episodes: 'Ongoing', image: 'assets/img/img_5.png'),
 AllAnime( unLiked: true,name: 'The Quintessential Quintuplets S1', episodes: '12', image: 'assets/img/img_6.png'),
 AllAnime( unLiked: true,name: 'The Quintessential Quintuplets S2', episodes: '12', image: 'assets/img/img_7.png'),
 AllAnime( unLiked: true,name: 'The Quintessential Quintuplets Movie', episodes: 'Movie', image: 'assets/img/img_8.png'),
 AllAnime( unLiked: true,name: "Alice and Therese's Illusory Factory", episodes: 'idn', image: 'assets/img/img_12.png'),
 AllAnime( unLiked: true,name: 'Amagi Brilliant Park S1', episodes: '7', image: 'assets/img/img_16.png'),
 AllAnime( unLiked: true,name: 'Amagi Brilliant Park S2', episodes: '13', image: 'assets/img/img_17.png'),
 AllAnime( unLiked: true,name: "Amagi Brilliant Park Movie", episodes: 'Full', image: 'assets/img/img_18.png'),
 AllAnime(unLiked:true,name: 'Angels of Death', episodes: '16', image: 'assets/img/img_19.png'),
 AllAnime(unLiked:true,name: 'Blue Spring Ride', episodes: '12', image: 'assets/img/img_20.png'),
 AllAnime(unLiked:true,name: 'Blue Spring Ride Movie', episodes: '2', image: 'assets/img/img_21.png'),
 AllAnime(unLiked:true,name: 'Are you Lost', episodes: '12', image: 'assets/img/img_22.png'),
 AllAnime(unLiked:true,name: 'Are you Willing to Fall in Love With a Pervert Because she is cutie', episodes: '12', image: 'assets/img/img_23.png'),
 AllAnime(unLiked:true,name: 'Art Club Has a Problem', episodes: '12', image: 'assets/img/img_24.png'),
 AllAnime(unLiked:true,name: "Aura: Koga Maryuin's Last Year Movie", episodes: 'Full', image: 'assets/img/img_25.png'),
 AllAnime(unLiked:true,name: 'Berserk of Gluttony', episodes: 'Ongoing', image: 'assets/img/img_26.png'),
 AllAnime(unLiked:true,name: 'Citrus', episodes: '12', image: 'assets/img/img_27.png'),
 AllAnime(unLiked:true,name: 'Aishen Qiaokeli-ing...|| S1', episodes: '15', image: 'assets/img/img_28.png'),
 AllAnime(unLiked:true,name: 'Aishen Qiaokeli-ing...|| S2', episodes: '15', image: 'assets/img/img_29.png'),
 AllAnime(unLiked:true,name: 'Daily Life of The Immortal King S1', episodes: '15', image: 'assets/img/img_30.png'),
 AllAnime(unLiked:true,name: 'Daily Life of The Immortal King S2', episodes: '12', image: 'assets/img/img_31.png'),
 AllAnime(unLiked:true,name: 'Daily Life of The Immortal King S3', episodes: '12', image: 'assets/img/img_32.png'),
 AllAnime(unLiked:true,name: 'Demon Sword Master of Excalibur Academy', episodes: 'Ongoing', image: 'assets/img/img_33.png'),
 AllAnime(unLiked:true,name: 'Another', episodes: '12', image: 'assets/img/img_38.png'),
 AllAnime(unLiked:false,name: 'A Couple of Cuckoos', episodes: '24', image: 'assets/img/img_39.png'),
 AllAnime(unLiked:true,name: 'Domestic Girlfriend', episodes: '12', image: 'assets/img/img_40.png'),
 AllAnime(unLiked:true,name: 'Engage Kiss', episodes: '12', image: 'assets/img/img_41.png'),
 AllAnime(unLiked:true,name: 'From Me to You S1', episodes: '26', image: 'assets/img/img_42.png'),
 AllAnime(unLiked:true,name: 'From Me to You S2', episodes: '12', image: 'assets/img/img_43.png'),
 AllAnime(unLiked:true,name: 'From Me to You Movie', episodes: 'Full', image: 'assets/img/img_44.png'),
 AllAnime(unLiked:true,name: 'Fruits Basket (2019) S1', episodes: '25', image: 'assets/img/img_45.png'),
 AllAnime(unLiked:true,name: 'Fruits Basket (2019) S2', episodes: '25', image: 'assets/img/img_46.png'),
 AllAnime(unLiked:true,name: 'Fruits Basket (2019) S3', episodes: '13', image: 'assets/img/img_47.png'),
 AllAnime(unLiked:true,name: 'Girlfriend, Girlfriend S1', episodes: '12', image: 'assets/img/img_48.png'),
 AllAnime(unLiked:true,name: 'Girlfriend, Girlfriend S2', episodes: 'Ongoing', image: 'assets/img/img_49.png'),
 AllAnime(unLiked:true,name: 'God of High-School', episodes: '13', image: 'assets/img/img_50.png'),
 AllAnime(unLiked:true,name: 'Hanada-kun', episodes: '12', image: 'assets/img/img_51.png'),
 AllAnime(unLiked:true,name: 'Hello World Movie', episodes: 'Full', image: 'assets/img/img_52.png'),
 AllAnime(unLiked:true,name: 'Horimiya S1', episodes: '13', image: 'assets/img/img_53.png'),
 AllAnime(unLiked:true,name: 'Horimiya S2', episodes: '13', image: 'assets/img/img_54.png'),
 AllAnime(unLiked:true,name: 'Hyouka', episodes: '22', image: 'assets/img/img_56.png'),
 AllAnime(unLiked:true,name: 'I am Giving the Disgraced Noble Lady I Rescued a Crash Course in Naughtiness', episodes: 'Ongoing', image: 'assets/img/img_58.png'),
 AllAnime(unLiked:true,name: 'I Got a Cheat Skill in Another World', episodes: '13', image: 'assets/img/img_59.png'),
 AllAnime(unLiked:true,name: 'Idoly Pride', episodes: '12', image: 'assets/img/img_60.png'),
 AllAnime(unLiked:true,name: 'Summoned to Another World for a Second Time', episodes: '12', image: 'assets/img/img_61.png'),
 AllAnime(unLiked:false,name: 'Mushoku Tensei: Jobless Reincarnation S1', episodes: '24', image: 'assets/img/img_62.png'),
 AllAnime(unLiked:false,name: 'Mushoku Tensei: Jobless Reincarnation S2', episodes: '13', image: 'assets/img/img_63.png'),
 AllAnime(unLiked:true,name: 'Kaguya Sama Love Is War S1', episodes: '12', image: 'assets/img/img_64.png'),
 AllAnime(unLiked:true,name: 'Kaguya Sama Love Is War S2', episodes: '12', image: 'assets/img/img_65.png'),
 AllAnime(unLiked:true,name: 'Kaguya Sama Love Is War S3', episodes: '13', image: 'assets/img/img_66.png'),
 AllAnime(unLiked:true,name: 'Kaguya Sama Love Is War:The First Kiss Never Ends', episodes: '2', image: 'assets/img/img_67.png'),
 AllAnime(unLiked:true,name: 'Lookism', episodes: '8', image: 'assets/img/img_70.png'),
 AllAnime(unLiked:true,name: 'Love Flops', episodes: '12', image: 'assets/img/img_73.png'),
 AllAnime(unLiked:true,name: 'Lycoris Recoil', episodes: '13', image: 'assets/img/img_74.png'),
 AllAnime(unLiked:true,name: 'Masemune-kuns Revenge S1', episodes: '12', image: 'assets/img/img_75.png'),
 AllAnime(unLiked:true,name: 'Masemune-kuns Revenge S2', episodes: '13', image: 'assets/img/img_76.png'),
 AllAnime(unLiked:true,name: 'Masemune-kuns Revenge Movie', episodes: 'Full', image: 'assets/img/img_77.png'),
 AllAnime(unLiked:false,name: 'More Than a Married But Not Lovers', episodes: '12', image: 'assets/img/img_79.png'),
 AllAnime(unLiked:true,name: 'My Dress-Up Darling', episodes: '12', image: 'assets/img/img_80.png'),
 AllAnime(unLiked:true,name: 'My Little Monster', episodes: '13', image: 'assets/img/img_81.png'),
 AllAnime(unLiked:true,name: 'My Little Sister Is Among Them', episodes: '12', image: 'assets/img/img_82.png'),
 AllAnime(unLiked:true,name: 'My Sister My Writer', episodes: '10', image: 'assets/img/img_84.png'),
 AllAnime(unLiked:true,name: 'Ore ga suki nano wa Imouto dakedo Imouto ja nai specials', episodes: '2', image: 'assets/img/img_85.png'),
 AllAnime(unLiked:true,name: 'My Stepsister Is My Ex-girlfriend', episodes: '12', image: 'assets/img/img_86.png'),
 AllAnime(unLiked:true,name: 'My Teen romantic Comedy Is Wrong As I expected S1', episodes: '13', image: 'assets/img/img_87.png'),
 AllAnime(unLiked:true,name: 'My Teen romantic Comedy Is Wrong As I expected S2', episodes: '13', image: 'assets/img/img_88.png'),
 AllAnime(unLiked:true,name: 'My Teen romantic Comedy Is Wrong As I expected S3', episodes: '12', image: 'assets/img/img_89.png'),
 AllAnime(unLiked:true,name: 'My Teen romantic Comedy Is Wrong As I expected Movie', episodes: '2', image: 'assets/img/img_90.png'),
 AllAnime(unLiked:true,name: 'Myriad Colors Phantom World', episodes: '13', image: 'assets/img/img_91.png'),
 AllAnime(unLiked:true,name: 'Myriad Colors Phantom World', episodes: 'Full', image: 'assets/img/img_92.png'),
 AllAnime(unLiked:true,name: 'OniAi S1', episodes: '12', image: 'assets/img/img_97.png'),
 AllAnime(unLiked:true,name: 'OniAi S2', episodes: '6', image: 'assets/img/img_98.png'),
 AllAnime(unLiked:true,name: 'Oreshura', episodes: '13', image: 'assets/img/img_99.png'),
 AllAnime(unLiked:false,name: 'Rascal Does Not Dream of Bunny Girl Senpai', episodes: '12', image: 'assets/img/img_100.png'),
 AllAnime(unLiked:false,name: 'Rascal Does Not Dream of Dreamy Girl Movie', episodes: 'Full', image: 'assetses/img/img_32.png'),
 AllAnime(unLiked:true,name: 'Shikimori Is Not Just a Cutie S1', episodes: '12', image: 'assetses/img/img_7.png'),
 AllAnime(unLiked:true,name: 'Shikimori Is Not Just a Cutie Movie', episodes: '2', image: 'assetses/img/img_8.png'),
 AllAnime(unLiked:true,name: 'Shine Post', episodes: '12', image: 'assetses/img/img_9.png'),
 AllAnime(unLiked:true,name: 'Shinobi no Ittoki', episodes: '12', image: 'assetses/img/img_10.png'),
 AllAnime(unLiked:true,name: 'Snow White with red hair S1', episodes: '12', image: 'assetses/img/img_11.png'),
 AllAnime(unLiked:true,name: 'Snow White with red hair S2', episodes: '12', image: 'assetses/img/img_12.png'),
 AllAnime(unLiked:false,name: 'Our Dating Story: The Experienced You And The Inexperienced Me', episodes: 'Ongoing', image: 'assetses/img/img_15.png'),
 AllAnime(unLiked:true,name: 'The Girl And Guard Dog', episodes: 'Ongoing', image: 'assetses/img/img_16.png'),
 AllAnime(unLiked:true,name: 'The Girl Downstairs', episodes: '22', image: 'assetses/img/img_17.png'),
 AllAnime(unLiked:false,name: 'The Kingdom Of Ruins', episodes: 'Ongoing', image: 'assetses/img/img_18.png'),
 AllAnime(unLiked:true,name: 'The Tunnel To Summer: The Exist Of Goodbye', episodes: 'Full', image: 'assetses/img/img_20.png'),
 AllAnime(unLiked:true,name: 'The Vexations Of a Shut-In Vampire Princess', episodes: 'Ongoing', image: 'assetses/img/img_21.png'),
 AllAnime(unLiked:true,name: 'The Eminence In Shadow S2', episodes: 'Ongoing', image: 'assetses/img/img_22.png'),
 AllAnime(unLiked:true,name: 'Tomo-chan Is a Girl', episodes: '13', image: 'assetses/img/img_23.png'),
 AllAnime(unLiked:true,name: 'Twin Star Exorcists', episodes: '50', image: 'assetses/img/img_24.png'),
 AllAnime(unLiked:true,name: 'Welcome To The Ballroom', episodes: '24', image: 'assetses/img/img_26.png'),
 AllAnime(unLiked:true,name: 'Witch Craft Works', episodes: '12', image: 'assetses/img/img_27.png'),
 AllAnime(unLiked:true,name: 'Yamada-kun And The Seven Witches', episodes: '12', image: 'assetses/img/img_28.png'),
 AllAnime(unLiked:true,name: 'Loving Yamada-Kun at 999lvl', episodes: '13', image: 'assetses/img/img_29.png'),
 AllAnime(unLiked:true,name: 'Your Name', episodes: 'Full', image: 'assetses/img/img_30.png'),
 AllAnime(unLiked:true,name: 'Zom 100 The Bucket List Of Dead', episodes: 'Ongoing', image: 'assetses/img/img_31.png'),
];
