import 'package:current_watching_anime/bottom_navigation_bar_sc/finished.dart';

class FinishedModel {
  String name;
  String episodes;
  String image;
  bool unLiked;

  FinishedModel({required this.unLiked,required this.name,required this.episodes,required this.image});
}

final finishedList = [
  FinishedModel(unLiked: true, name: "My First Girlfriend is a Gal", episodes: "12", image: "assets/picture/img_21.png"),
  FinishedModel(unLiked: true, name: "Bottom-Tier Character Season 1", episodes: "12", image: "assets/picture/img_19.png"),
  FinishedModel(unLiked: true, name: "Chivalry Of A Failed Knight", episodes: "12", image: "assets/picture/img_18.png"),
  FinishedModel(unLiked: true, name: "Jujutsu Kaisen S2", episodes: "23", image: "assets/picture/img_8.png"),
  FinishedModel(unLiked:true,name: 'I Got a Cheat Skill in Another World', episodes: '13', image: 'assets/img/img_59.png'),
  FinishedModel(unLiked: true, name: "Yosuga No Sora", episodes: "12", image: "assets/picture/img_15.png"),
  FinishedModel(unLiked: true, name: "Jujutsu Kaisen S1", episodes: "24", image: "assets/picture/img_7.png"),
  FinishedModel(unLiked: true, name: "Redo of healers", episodes: "12", image: "assets/picture/img_14.png"),
  FinishedModel(unLiked:true,name: 'Myriad Colors Phantom World', episodes: '13', image: 'assets/img/img_93.png'),
  FinishedModel(unLiked: true, name: "Worlds end harem", episodes: "12", image: "assets/picture/img_13.png"),
  FinishedModel(unLiked:true,name: 'Lycoris Recoil', episodes: '13', image: 'assets/img/img_74.png'),
  FinishedModel(unLiked: false, name: "Darling in th franxx", episodes: "24", image: "assets/picture/img_9.png"),
  FinishedModel(unLiked: true, name: "So I Can't play H", episodes: "12", image: "assets/picture/img_12.png"),
  FinishedModel(unLiked: true, name: "Absolute Duo", episodes: "12", image: "assets/picture/img_11.png"),
  FinishedModel(unLiked: false, name: "Chainsaw Man", episodes: "12", image: "assets/picture/img_6.png"),
  FinishedModel(unLiked: true, name: "Rascal does not dream sister venturing out", episodes: 'Full', image: "assets/picture/img_4.png"),
  FinishedModel(unLiked: true, name: "Rent a Girlfriend S3", episodes: "12", image:"assets/picture/img_3.png"),
  FinishedModel(unLiked: true, name: "Rent a Girlfriend S2", episodes: "12", image:"assets/picture/img_2.png"),
  FinishedModel(unLiked:true,name: 'I am Giving the Disgraced Noble Lady I Rescued a Crash Course in Naughtiness', episodes: '12', image: 'assets/img/img_58.png'),
  FinishedModel(unLiked: true, name: "Rent a Girlfriend S1", episodes: "12", image:"assets/picture/img_1.png"),
  FinishedModel(unLiked: true, name: "Momokuri", episodes: "13", image: "assets/picture/img.png"),
  FinishedModel(unLiked: true, name: "Gamers", episodes: "12", image: "assetses/img/img_35.png"),
  FinishedModel(unLiked: true, name: "Over the sky", episodes: 'Full', image: 'assetses/img/img_33.png'),
  FinishedModel( unLiked: true,name: 'Amagi Brilliant Park S1', episodes: '12', image: 'assets/img/img_16.png'),
  FinishedModel(unLiked:false,name: 'Our Dating Story: The Experienced You And The Inexperienced Me', episodes: '12', image: 'assetses/img/img_15.png'),
  FinishedModel(unLiked:true, name: 'Girlfriend, Girlfriend S2', episodes: '12', image: 'assets/img/img_49.png'),
  FinishedModel(unLiked: true, name: 'Romantic Killer', episodes: '12', image: 'assetses/img/img_14.png'),
  FinishedModel(unLiked: true, name: 'The galaxy next door', episodes: '12', image: 'assetses/img/img_3.png'),
  FinishedModel(unLiked: true, name: 'Black Summoner', episodes: '12', image: 'assetses/img/img_1.png'),
  FinishedModel(unLiked: true,name: 'The Eminence in Shadow S1', episodes: '20', image: 'assets/img/img.png',),
  FinishedModel(unLiked: false,name: 'My Star', episodes: '12', image: 'assets/img/img_1.png'),
  FinishedModel(unLiked: false,name: 'The Angel Next Door Spoils Me Rotten', episodes: '12', image: 'assets/img/img_2.png'),
  FinishedModel(unLiked: true,name: 'The Quintessential Quintuplets S1', episodes: '12', image: 'assets/img/img_6.png'),
  FinishedModel(unLiked: true,name: 'The Quintessential Quintuplets S2', episodes: '12', image: 'assets/img/img_7.png'),
  FinishedModel(unLiked: true,name: 'The Quintessential Quintuplets Movie', episodes: 'Movie', image: 'assets/img/img_8.png'),
  FinishedModel(unLiked:true,name: 'Another', episodes: '12', image: 'assets/img/img_38.png'),
  FinishedModel(unLiked:false,name: 'A Couple of Cuckoos', episodes: '24', image: 'assets/img/img_39.png'),
  FinishedModel(unLiked:true,name: 'Domestic Girlfriend', episodes: '12', image: 'assets/img/img_40.png'),
  FinishedModel(unLiked:true,name: 'Engage Kiss', episodes: '12', image: 'assets/img/img_41.png'),
  FinishedModel(unLiked:true,name: 'Hello World Movie', episodes: 'Full', image: 'assets/img/img_52.png'),
  FinishedModel(unLiked:true,name: 'Horimiya S1', episodes: '13', image: 'assets/img/img_53.png'),
  FinishedModel(unLiked:true,name: 'Hyouka', episodes: '22', image: 'assets/img/img_56.png'),
  FinishedModel(unLiked:false,name: 'Mushoku Tensei: Jobless Reincarnation S1', episodes: '24', image: 'assets/img/img_62.png'),
  FinishedModel(unLiked:false,name: 'Mushoku Tensei: Jobless Reincarnation S2', episodes: '13', image: 'assets/img/img_63.png'),
  FinishedModel(unLiked:true,name: 'Lookism', episodes: '8', image: 'assets/img/img_70.png'),
  FinishedModel(unLiked:true,name: 'Masemune-kuns Revenge S1', episodes: '12', image: 'assets/img/img_75.png'),
  FinishedModel(unLiked:true,name: 'Masemune-kuns Revenge S2', episodes: '13', image: 'assets/img/img_76.png'),
  FinishedModel(unLiked:true,name: 'Masemune-kuns Revenge Movie', episodes: 'Full', image: 'assets/img/img_77.png'),
  FinishedModel(unLiked:false,name: 'More Than a Married But Not Lovers', episodes: '12', image: 'assets/img/img_79.png'),
  FinishedModel(unLiked:true,name: 'my Dress-Up Darling', episodes: '12', image: 'assets/img/img_80.png'),
  FinishedModel(unLiked:true,name: 'My Stepsister Is My Ex-girlfriend', episodes: '12', image: 'assets/img/img_86.png'),
  FinishedModel(unLiked:true,name: 'Oreshura', episodes: '13', image: 'assets/img/img_99.png'),
  FinishedModel(unLiked:false,name: 'Rascal Does Not Dream of Bunny Girl Senpai', episodes: '12', image: 'assets/img/img_100.png'),
  FinishedModel(unLiked:false,name: 'Rascal Does Not Dream of Dreamy Girl Movie', episodes: 'Full', image: 'assetses/img/img_32.png'),
  FinishedModel(unLiked:true,name: 'Shikimori Is Not Just a Cutie S1', episodes: '12', image: 'assetses/img/img_7.png'),
  FinishedModel(unLiked:true,name: 'The Tunnel To Summer: The Exist Of Goodbye', episodes: 'Full', image: 'assetses/img/img_20.png'),
  FinishedModel(unLiked:true,name: 'Yamada-kun And The Seven Witches', episodes: '12', image: 'assetses/img/img_28.png'),
  FinishedModel(unLiked:true,name: 'Loving Yamada-Kun at 999lvl', episodes: '13', image: 'assetses/img/img_29.png'),
  FinishedModel(unLiked:true,name: 'Your Name', episodes: 'Full', image: 'assetses/img/img_30.png'),
  FinishedModel(unLiked:true,name: 'Zom 100 The Bucket List Of Dead s2', episodes: '12', image: 'assetses/img/img_31.png'),
  FinishedModel(unLiked:true,name: 'Girlfriend, Girlfriend S1', episodes: '12', image: 'assets/img/img_48.png'),
  FinishedModel(unLiked:true,name: 'Hyouka', episodes: '22', image: 'assets/img/img_56.png'),
  FinishedModel(unLiked:true,name: 'Are you Willing to Fall in Love With a Pervert Because she is cutie', episodes: '12', image: 'assets/img/img_23.png'),
];